### PR TITLE
Update to 1.12.2 (API 7)

### PR DESCRIPTION
**Pull request by Sandvoxel**
A quick and dirty update to 1.12.2 and API 7

### CODE REVIEW

**Comment by randombyte-developer** [comment]
Nice! Could you remove the author string in the data id and name? And change that all together rather to a hard coded strings "holograms-data" and "Holograms data".

**Comment by Sandvoxel** [comment]
Will do

**Comment by randombyte-developer** [comment]
Thanks for your effort!

**Comment by Sandvoxel** [comment]
No problem

**Pull request merged**
